### ISSUE TITLE
Code base have potential nil pointer exceptions

### ISSUE THREAD

**Issue by Selahattinn** [limanmys/limanctl#2]
some of them can be null and system wants to reach their subfields. You should check before reach. They can be nil. 
You can think like ı am adding it beacuse of that I am controling it but this is a system and ı can add a value with connecting db manualy.

https://github.com/limanmys/limanctl/blob/02aed0b8e58c8e03c996274cd9faf6d8642e89ad/cmd/list_users.go#L21-L37

example fix:
```
func listUsers() {
	db := helpers.DB

	var users []models.User
	if result := db.Find(&users); result.Error != nil {
		log.Fatal("User not found on Liman")
	}

	table := tablewriter.NewWriter(os.Stdout)
	table.SetHeader([]string{"User Type", "Name", "E-mail", "Last Login At", "Last Login IP", "Auth Type"})

	for _, v := range users {
		var userType, lastLoginAt, lastLoginIP string

		// Determine user type based on Status
		if v.Status == 1 {
			userType = "Admin"
		} else {
			userType = "User"
		}

		// Handle potential NULL values for LastLoginAt and LastLoginIP
		if v.LastLoginAt.Valid {
			lastLoginAt = v.LastLoginAt.String
		} else {
			lastLoginAt = "N/A"
		}

		if v.LastLoginIP.Valid {
			lastLoginIP = v.LastLoginIP.String
		} else {
			lastLoginIP = "N/A"
		}

		// Append data to table
		table.Append([]string{
			userType, v.Name, v.Email, lastLoginAt, lastLoginIP, v.AuthType,
		})
	}

	table.Render()
}
```

**Comment by dogukanoksuz** [comment]
Because that we use go-pg, this nil fields filled by orm automatically. So we don't need to check whether fields is nil or not

![image](https://github.com/user-attachments/assets/519a049b-239d-4f0c-9da0-6669af948fc8)

Thanks for creating an issue on our library. Have a great day.
